<a href="https://colab.research.google.com/github/BySowy8/ObraTrack/blob/Rama-Angel/ObraTrack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install supabase

Collecting supabase
  Downloading supabase-2.31.0-py3-none-any.whl.metadata (4.7 kB)
Collecting realtime==2.31.0 (from supabase)
  Downloading realtime-2.31.0-py3-none-any.whl.metadata (7.0 kB)
Collecting supabase-functions==2.31.0 (from supabase)
  Downloading supabase_functions-2.31.0-py3-none-any.whl.metadata (2.4 kB)
Collecting storage3==2.31.0 (from supabase)
  Downloading storage3-2.31.0-py3-none-any.whl.metadata (2.2 kB)
Collecting supabase-auth==2.31.0 (from supabase)
  Downloading supabase_auth-2.31.0-py3-none-any.whl.metadata (6.4 kB)
Collecting postgrest==2.31.0 (from supabase)
  Downloading postgrest-2.31.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: httpx<0.29,>=0.26 in /usr/local/lib/python3.13/dist-packages (from supabase) (0.28.1)
Requirement already satisfied: yarl>=1.22.0 in /usr/local/lib/python3.13/dist-packages (from supabase) (1.24.5)
Requirement already satisfied: deprecation>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from postgrest==2.31.0->supabase) (2.1.0)
Requirement already satisfied: pydantic<3.0,>=1.9 in /usr/local/lib/python3.13/dist-packages (from postgrest==2.31.0->supabase) (2.13.4)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from realtime==2.31.0->supabase) (4.16.0)
Requirement already satisfied: websockets<16,>=11 in /usr/local/lib/python3.13/dist-packages (from realtime==2.31.0->supabase) (15.0.1)
Requirement already satisfied: pyjwt>=2.12.0 in /usr/local/lib/python3.13/dist-packages (from pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase) (2.13.0)
Collecting strenum>=0.4.15 (from supabase-functions==2.31.0->supabase)
  Downloading StrEnum-0.4.15-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<0.29,>=0.26->supabase) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<0.29,>=0.26->supabase) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<0.29,>=0.26->supabase) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<0.29,>=0.26->supabase) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<0.29,>=0.26->supabase) (0.16.0)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.13/dist-packages (from yarl>=1.22.0->supabase) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from yarl>=1.22.0->supabase) (0.5.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from deprecation>=2.1.0->postgrest==2.31.0->supabase) (26.3)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.13/dist-packages (from httpx[http2]<0.29,>=0.26->postgrest==2.31.0->supabase) (4.4.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.31.0->supabase) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.31.0->supabase) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.31.0->supabase) (0.4.4)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.13/dist-packages (from pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase) (50.0.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase) (2.1.1)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.13/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.31.0->supabase) (6.1.0)
Requirement already satisfied: hpack<5,>=4.2 in /usr/local/lib/python3.13/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.31.0->supabase) (4.2.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=3.4.0->pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase) (3.0)
Downloading supabase-2.31.0-py3-none-any.whl (16 kB)
Downloading postgrest-2.31.0-py3-none-any.whl (23 kB)
Downloading realtime-2.31.0-py3-none-any.whl (22 kB)
Downloading storage3-2.31.0-py3-none-any.whl (28 kB)
Downloading supabase_auth-2.31.0-py3-none-any.whl (48 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 1.2 MB/s eta 0:00:00
Downloading supabase_functions-2.31.0-py3-none-any.whl (8.8 kB)
Downloading StrEnum-0.4.15-py3-none-any.whl (8.9 kB)
Installing collected packages: strenum, realtime, supabase-functions, supabase-auth, storage3, postgrest, supabase
Successfully installed postgrest-2.31.0 realtime-2.31.0 storage3-2.31.0 strenum-0.4.15 supabase-2.31.0 supabase-auth-2.31.0 supabase-functions-2.31.0

In [2]:
!unzip -o /content/obratrack-hu2.zip -d /content/temp_hu2

unzip:  cannot find or open /content/obratrack-hu2.zip, /content/obratrack-hu2.zip.zip or /content/obratrack-hu2.zip.ZIP.

In [ ]:
!ls /content/temp_hu2

obratrack-hu2

In [ ]:
from supabase import create_client

url = "https://syosgdsranzmrajczgrd.supabase.co/rest/v1/"       # tu Project URL
key = "sb_publishable_P-zjN2qYgSN5Q6joPb36eA_AZR9W1Hw"                           # tu anon public key

supabase = create_client(url, key)

In [ ]:
!ls /content

sample_data

In [ ]:
!unzip

UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
  Default action is to extract files in list, except those in xlist, to exdir;
  file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

  -p  extract files to pipe, no messages     -l  list files (short format)
  -f  freshen existing files, create none    -t  test compressed archive data
  -u  update files, create if necessary      -z  display archive comment only
  -v  list verbosely/show version info       -T  timestamp archive to latest
  -x  exclude files that follow (in xlist)   -d  extract files into exdir
modifiers:
  -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
  -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
  -j  junk paths (do not make directories)   -aa treat ALL files as text
  -U  use escapes for all non-ASCII Unicode  -UU ignore any Unicode fields
  -C  match filenames case-insensitively     -L  make (some) names lowercase
  -X  restore UID/GID info                   -V  retain VMS version numbers
  -K  keep setuid/setgid/tacky permissions   -M  pipe through "more" pager
  -O CHARSET  specify a character encoding for DOS, Windows and OS/2 archives
  -I CHARSET  specify a character encoding for UNIX and other archives

See "unzip -hh" or unzip.txt for more help.  Examples:
  unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
  unzip -p foo | more  => send contents of foo.zip via pipe into program more
  unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer

In [ ]:
%cd /content/ObraTrack

!rm -rf ObraTrack


!rm -f schema.sql env.example download


!printf ".env\n__pycache__/\n*.pyc\n.ipynb_checkpoints/\n.venv/\n" > .gitignore


!find /content/ObraTrack -type f -not -path "*/.git/*" | sort

/content/ObraTrack
/content/ObraTrack/.env.example
/content/ObraTrack/.gitignore
/content/ObraTrack/main.py
/content/ObraTrack/models.py
/content/ObraTrack/ObraTrack_HU2_Colab.ipynb
/content/ObraTrack/ObraTrack.ipynb
/content/ObraTrack/README.md
/content/ObraTrack/requirements.txt
/content/ObraTrack/routers/imprevistos.py
/content/ObraTrack/routers/__init__.py
/content/ObraTrack/sql/schema.sql
/content/ObraTrack/supabase_client.py
/content/ObraTrack/tests/prueba_manual.py

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Sube todos los archivos creados al repositorio
!git add .
!git config user.name "TuNombreEnGitHub"
!git config user.email "tu_correo@ejemplo.com"
!git commit -m "Estructura completa de HU2 e imprevistos lista"
!git push origin Rama-Jean

[Rama-Jean 6daea53] Estructura completa de HU2 e imprevistos lista
 12 files changed, 812 insertions(+), 2 deletions(-)
 create mode 100644 .env.example
 create mode 100644 .gitignore
 create mode 100644 ObraTrack_HU2_Colab.ipynb
 rewrite README.md (100%)
 create mode 100644 main.py
 create mode 100644 models.py
 create mode 100644 requirements.txt
 create mode 100644 routers/__init__.py
 create mode 100644 routers/imprevistos.py
 create mode 100644 sql/schema.sql
 create mode 100644 supabase_client.py
 create mode 100644 tests/prueba_manual.py
fatal: could not read Username for 'https://github.com': No such device or address

In [ ]:
!git clone https://github.com/BySowy8/ObraTrack.git

Cloning into 'ObraTrack'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 36 (delta 13), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (36/36), 10.15 KiB | 10.15 MiB/s, done.
Resolving deltas: 100% (13/13), done.

In [ ]:
%cd ObraTrack
!git checkout Rama-Jean

/content/ObraTrack
Branch 'Rama-Jean' set up to track remote branch 'Rama-Jean' from 'origin'.
Switched to a new branch 'Rama-Jean'

In [ ]:

!git clone https://github.com/BySowy8/ObraTrack.git

%cd ObraTrack


!git checkout Rama-Cristhian

Cloning into 'ObraTrack'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 39 (delta 14), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (39/39), 12.73 KiB | 766.00 KiB/s, done.
Resolving deltas: 100% (14/14), done.
/content/ObraTrack
Branch 'Rama-Cristhian' set up to track remote branch 'Rama-Cristhian' from 'origin'.
Switched to a new branch 'Rama-Cristhian'

In [ ]:
# 1. Instalamos la librería oficial de Supabase
!pip install supabase pandas

# 2. Importamos la librería
from supabase import create_client

# 3. Datos de conexión limpios
url = "https://syosgdsranzmrajczgrd.supabase.co"
key = "sb_publishable_P-zjN2qYgSN5Q6joPb36eA_AZR9W1Hw"

# 4. Inicializamos el cliente
supabase = create_client(url, key)

print(" Conexión a Supabase configurada exitosamente.")

Collecting supabase
  Downloading supabase-2.31.0-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Collecting realtime==2.31.0 (from supabase)
  Downloading realtime-2.31.0-py3-none-any.whl.metadata (7.0 kB)
Collecting supabase-functions==2.31.0 (from supabase)
  Downloading supabase_functions-2.31.0-py3-none-any.whl.metadata (2.4 kB)
Collecting storage3==2.31.0 (from supabase)
  Downloading storage3-2.31.0-py3-none-any.whl.metadata (2.2 kB)
Collecting supabase-auth==2.31.0 (from supabase)
  Downloading supabase_auth-2.31.0-py3-none-any.whl.metadata (6.4 kB)
Collecting postgrest==2.31.0 (from supabase)
  Downloading postgrest-2.31.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: httpx<0.29,>=0.26 in /usr/local/lib/python3.13/dist-packages (from supabase) (0.28.1)
Requirement already satisfied: yarl>=1.22.0 in /usr/local/lib/python3.13/dist-packages (from supabase) (1.24.5)
Requirement already satisfied: deprecation>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from postgrest==2.31.0->supabase) (2.1.0)
Requirement already satisfied: pydantic<3.0,>=1.9 in /usr/local/lib/python3.13/dist-packages (from postgrest==2.31.0->supabase) (2.13.4)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from realtime==2.31.0->supabase) (4.16.0)
Requirement already satisfied: websockets<16,>=11 in /usr/local/lib/python3.13/dist-packages (from realtime==2.31.0->supabase) (15.0.1)
Requirement already satisfied: pyjwt>=2.12.0 in /usr/local/lib/python3.13/dist-packages (from pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase) (2.13.0)
Collecting strenum>=0.4.15 (from supabase-functions==2.31.0->supabase)
  Downloading StrEnum-0.4.15-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<0.29,>=0.26->supabase) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<0.29,>=0.26->supabase) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<0.29,>=0.26->supabase) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<0.29,>=0.26->supabase) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<0.29,>=0.26->supabase) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.13/dist-packages (from yarl>=1.22.0->supabase) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from yarl>=1.22.0->supabase) (0.5.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from deprecation>=2.1.0->postgrest==2.31.0->supabase) (26.3)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.13/dist-packages (from httpx[http2]<0.29,>=0.26->postgrest==2.31.0->supabase) (4.4.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.31.0->supabase) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.31.0->supabase) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.31.0->supabase) (0.4.4)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.13/dist-packages (from pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase) (50.0.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase) (2.1.1)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.13/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.31.0->supabase) (6.1.0)
Requirement already satisfied: hpack<5,>=4.2 in /usr/local/lib/python3.13/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.31.0->supabase) (4.2.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=3.4.0->pyjwt[crypto]>=2.12.0->supabase-auth==2.31.0->supabase) (3.0)
Downloading supabase-2.31.0-py3-none-any.whl (16 kB)
Downloading postgrest-2.31.0-py3-none-any.whl (23 kB)
Downloading realtime-2.31.0-py3-none-any.whl (22 kB)
Downloading storage3-2.31.0-py3-none-any.whl (28 kB)
Downloading supabase_auth-2.31.0-py3-none-any.whl (48 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 4.1 MB/s eta 0:00:00
Downloading supabase_functions-2.31.0-py3-none-any.whl (8.8 kB)
Downloading StrEnum-0.4.15-py3-none-any.whl (8.9 kB)
Installing collected packages: strenum, realtime, supabase-functions, supabase-auth, storage3, postgrest, supabase
Successfully installed postgrest-2.31.0 realtime-2.31.0 storage3-2.31.0 strenum-0.4.15 supabase-2.31.0 supabase-auth-2.31.0 supabase-functions-2.31.0
 Conexión a Supabase configurada exitosamente.

In [ ]:
from google.colab import drive; drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
!mkdir -p /content/drive/MyDrive/ObraTrack_Sprint1

In [ ]:
%cd /content/drive/MyDrive/ObraTrack_Sprint1
!git clone https://github.com/BySowy8/ObraTrack.git

/content/drive/MyDrive/ObraTrack_Sprint1
Cloning into 'ObraTrack'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 39 (delta 14), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (39/39), 12.73 KiB | 1002.00 KiB/s, done.
Resolving deltas: 100% (14/14), done.

In [ ]:
%cd ObraTrack
!git checkout Rama-Jean

/content/drive/MyDrive/ObraTrack_Sprint1/ObraTrack
Branch 'Rama-Jean' set up to track remote branch 'Rama-Jean' from 'origin'.
Switched to a new branch 'Rama-Jean'

In [ ]:
# Usamos la conexión 'supabase' ya creada previamente
try:
    respuesta = supabase.table("bitacora").select("*").execute()
    datos = respuesta.data

    if datos:
        print(f" Se encontraron {len(datos)} registros en la base de datos:")
        import pandas as pd
        df_bitacora = pd.DataFrame(datos)
        display(df_bitacora.head())
    else:
        print(" La tabla 'bitacora' existe pero aún no tiene datos insertados.")

except Exception as e:
    print(" Detalle al intentar consultar la tabla:")
    print(e)

 Detalle al intentar consultar la tabla:
name 'supabase' is not defined

In [ ]:
import pandas as pd

# 1. Traer datos ordenados por fecha de forma descendente
respuesta = supabase.table("bitacora").select("*").order("fecha", desc=True).execute()
datos = respuesta.data

# 2. Guardar en un DataFrame
df_bitacora = pd.DataFrame(datos)

# 3. Mostrar el resultado
print(f"✅ Conexión exitosa. Registros encontrados: {len(df_bitacora)}\n")
display(df_bitacora)

✅ Conexión exitosa. Registros encontrados: 0

Empty DataFrame
Columns: []
Index: []

In [ ]:
# Insertar registros de prueba a la tabla bitacora
nuevos_registros = [
    {
        "fecha": "2026-08-20",
        "descripcion_avance": "Vaciado de concreto en zapatas del sector A.",
        "imprevisto": None
    },
    {
        "fecha": "2026-08-21",
        "descripcion_avance": "Instalación de tuberías subterráneas.",
        "imprevisto": "Lluvia fuerte detuvo labores por 3 horas."
    }
]

# Insertar en Supabase
supabase.table("bitacora").insert(nuevos_registros).execute()
print(" Data de prueba insertada correctamente.")

APIError: {'message': 'new row violates row-level security policy for table "bitacora"', 'code': '42501', 'hint': None, 'details': None}

In [ ]:
# Consulta a la base de datos
respuesta = supabase.table("bitacora").select("*").order("fecha", desc=True).execute()
df_bitacora = pd.DataFrame(respuesta.data)

print(f" Registros encontrados: {len(df_bitacora)}\n")
display(df_bitacora)

 Registros encontrados: 0

Empty DataFrame
Columns: []
Index: []

In [ ]:
import pandas as pd
from IPython.display import display, HTML

# 1. Consultar los datos directamente desde Supabase
respuesta = supabase.table("bitacora").select("*").order("fecha", desc=True).execute()
df_bitacora = pd.DataFrame(respuesta.data)

# 2. Función de renderizado visual
def mostrar_historial_bitacora(df):
    if df is None or df.empty:
        print("⚠️ No hay registros para mostrar.")
        return

    html_code = """
    <style>
        .contenedor-bitacora {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 800px;
            margin: 0 auto;
        }
        .card-avance {
            border-radius: 8px;
            padding: 16px;
            margin-bottom: 16px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.08);
        }
        .sin-imprevisto {
            background-color: #f0fdf4;
            border-left: 6px solid #16a34a;
        }
        .con-imprevisto {
            background-color: #fef2f2;
            border-left: 6px solid #dc2626;
        }
        .header-card {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 8px;
            border-bottom: 1px solid rgba(0,0,0,0.05);
            padding-bottom: 6px;
        }
        .fecha {
            font-weight: bold;
            color: #334155;
        }
        .badge {
            padding: 4px 10px;
            border-radius: 12px;
            font-size: 0.85em;
            font-weight: bold;
        }
        .badge-success { background-color: #dcfce7; color: #15803d; }
        .badge-danger { background-color: #fee2e2; color: #b91c1c; }
        .texto-imprevisto {
            color: #991b1b;
            background-color: #fff1f1;
            padding: 8px 12px;
            border-radius: 6px;
            font-size: 0.9em;
            margin-top: 8px;
            border: 1px solid #fecaca;
        }
    </style>
    <div class="contenedor-bitacora">
        <h2 style="color: #0f172a; text-align: center; margin-bottom: 20px;">📋 Historial de Bitácora de Obra</h2>
    """

    for _, fila in df.iterrows():
        imprevisto_txt = str(fila.get('imprevisto', '')).strip()
        tiene_imprevisto = bool(imprevisto_txt and imprevisto_txt.lower() not in ['none', 'nan', 'null', ''])

        clase_card = "con-imprevisto" if tiene_imprevisto else "sin-imprevisto"
        badge_html = '<span class="badge badge-danger">🚨 Con Imprevisto</span>' if tiene_imprevisto else '<span class="badge badge-success">✅ Día Normal</span>'

        html_code += f"""
        <div class="card-avance {clase_card}">
            <div class="header-card">
                <span class="fecha">📅 Fecha: {fila.get('fecha', 'N/A')}</span>
                {badge_html}
            </div>
            <div><strong>Avance del día:</strong> {fila.get('descripcion_avance', 'Sin información')}</div>
        """

        if tiene_imprevisto:
            html_code += f"""
            <div class="texto-imprevisto">
                <strong>⚠️ Detalle del Imprevisto:</strong> {imprevisto_txt}
            </div>
            """

        html_code += "</div>"

    html_code += "</div>"
    display(HTML(html_code))

# 3. Mostrar el historial visual
mostrar_historial_bitacora(df_bitacora)

⚠️ No hay registros para mostrar.

In [ ]:
%%writefile modulo_historial.py
import pandas as pd
from IPython.display import display, HTML

def obtener_datos_bitacora(supabase_client):
    """Consulta la tabla bitacora y retorna un DataFrame."""
    try:
        respuesta = supabase_client.table("bitacora").select("*").order("fecha", desc=True).execute()
        return pd.DataFrame(respuesta.data)
    except Exception as e:
        print("❌ Error al consultar Supabase:", e)
        return pd.DataFrame()

def renderizar_historial_html(df):
    """Genera la interfaz visual responsiva con colores."""
    if df is None or df.empty:
        print("⚠️ No hay registros guardados en la bitácora todavía.")
        return

    html_code = """
    <style>
        .contenedor-bitacora { font-family: 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; }
        .card-avance { border-radius: 8px; padding: 16px; margin-bottom: 16px; box-shadow: 0 2px 4px rgba(0,0,0,0.08); }
        .sin-imprevisto { background-color: #f0fdf4; border-left: 6px solid #16a34a; }
        .con-imprevisto { background-color: #fef2f2; border-left: 6px solid #dc2626; }
        .header-card { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }
        .fecha { font-weight: bold; color: #334155; }
        .badge { padding: 4px 10px; border-radius: 12px; font-size: 0.85em; font-weight: bold; }
        .badge-success { background-color: #dcfce7; color: #15803d; }
        .badge-danger { background-color: #fee2e2; color: #b91c1c; }
        .texto-imprevisto { color: #991b1b; background-color: #fff1f1; padding: 8px 12px; border-radius: 6px; font-size: 0.9em; margin-top: 8px; border: 1px solid #fecaca; }
    </style>
    <div class="contenedor-bitacora">
        <h2 style="color: #0f172a; text-align: center; margin-bottom: 20px;">📋 Historial de Bitácora de Obra</h2>
    """

    for _, fila in df.iterrows():
        imprevisto_txt = str(fila.get('imprevisto', '')).strip()
        tiene_imprevisto = bool(imprevisto_txt and imprevisto_txt.lower() not in ['none', 'nan', 'null', ''])

        clase_card = "con-imprevisto" if tiene_imprevisto else "sin-imprevisto"
        badge_html = '<span class="badge badge-danger">🚨 Con Imprevisto</span>' if tiene_imprevisto else '<span class="badge badge-success">✅ Día Normal</span>'

        html_code += f"""
        <div class="card-avance {clase_card}">
            <div class="header-card">
                <span class="fecha">📅 Fecha: {fila.get('fecha', 'N/A')}</span>
                {badge_html}
            </div>
            <div><strong>Avance del día:</strong> {fila.get('descripcion_avance', 'Sin información')}</div>
        """

        if tiene_imprevisto:
            html_code += f"""
            <div class="texto-imprevisto">
                <strong>⚠️ Detalle del Imprevisto:</strong> {imprevisto_txt}
            </div>
            """

        html_code += "</div>"

    html_code += "</div>"
    display(HTML(html_code))

Writing modulo_historial.py

# 🛠️ HU3: Historial y Vista de Bitácora (Cristhian)

In [ ]:
# Importamos desde tu propio módulo separado
from modulo_historial import obtener_datos_bitacora, renderizar_historial_html

# 1. Obtener datos
df_bitacora = obtener_datos_bitacora(supabase)

# 2. Renderizar interfaz
renderizar_historial_html(df_bitacora)

# Registro de bitácora

In [3]:
from datetime import date

class Bitacora:
    def __init__(self, supabase_client, tabla="Bitacora"):
        self.supabase = supabase_client
        self.tabla = tabla

    def registrar_avance(self, descripcion: str, fecha: str = None):
        """
        Registra un nuevo reporte diario de avance de obra.
        - descripcion: texto describiendo el avance del día
        - fecha: formato 'YYYY-MM-DD'. Si no se especifica, usa la fecha de hoy.
        """
        if fecha is None:
            fecha = date.today().isoformat()

        data = {
            "descripcion": descripcion,
            "fecha": fecha
        }

        response = self.supabase.table(self.tabla).insert(data).execute()
        print(f"✅ Bitácora registrada: {descripcion} ({fecha})")
        return response

    def obtener_bitacoras(self):
        """Devuelve todos los registros de bitácora, ordenados por fecha descendente."""
        response = self.supabase.table(self.tabla).select("*").order("fecha", desc=True).execute()
        return response.data

    def obtener_por_fecha(self, fecha: str):
        """Filtra los registros de bitácora por una fecha específica."""
        response = self.supabase.table(self.tabla).select("*").eq("fecha", fecha).execute()
        return response.data